# update secret-env-cypher locally with:
# openssl aes-256-cbc -e -in secret-env-plain -out secret-env-cipher -k $KEY
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          # https://www.openssl.org/docs/faq.html#USER3
          command: |

            openssl aes-256-cbc -md md5 -d -in secret-env-cipher -k $KEY >> ~/.circlerc
            sudo apt-get update; sudo apt-get install gettext graphicsmagick
            sudo npm install -g grunt-cli gh@2.8.9
            source ~/.circlerc
            GITHUB_TOKEN=$GITHUB_TOKEN GITHUB_USER=$GITHUB_USER node scripts/ci-creds.js
            mkdir -p ~/.config/configstore/
            echo optOut: true > ~/.config/configstore/insight-gh.yml
            git config --global user.email "bugmirror@restmail.net"
            git config --global user.name "Bug Mirror"
            git remote rm origin
            git remote add origin git@github.com:bug-mirror/fxa-content-server-l10n.git

            ssh-agent -s > ~/.ssh_agent_conf;
            source ~/.ssh_agent_conf;

            ssh-add -D;
            openssl aes-256-cbc -md md5 -d -in id_bug_mirror.enc -k $KEY >> ~/.ssh/id_bug_mirror;
            chmod 0600 ~/.ssh/id_bug_mirror;
            ssh-add ~/.ssh/id_bug_mirror;

            bash ./scripts/extract-and-pull-request.sh; gh pr --submit mozilla --branch master --browser false;

  ci:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build-test-push:
    jobs:
      - ci

  send-pr:
    triggers:
      - schedule:
          cron: "0 22 * * 4" # At 15:00 PDT on Thursday
          filters:
            branches:
              only: master
    jobs:
      - build
